name: wap
wow-versions:
- 9.0.2
curseforge:
  project-id: 000000
  changelog: CHANGELOG.md
  addon-name: fill-this-in
dirs:
- path: wap
  toc:
    tags:
      Title: wap
      Author: Your name
      Notes: The description of your addon...
      DefaultState: Enabled
      LoadOnDemand: 0
    files:
    - wap.lua

