name: 'Install wap dependencies'
description: 'Installs poetry and the dependencies of wap'
inputs:
  pip-cache-key:
    description: 'The key for the pip cache'
    required: true
  poetry-cache-key:
    description: 'The key for the poetry cache'
    required: true
runs:
  using: "composite"
  steps:
    - name: Get pip cache dir
      id: pip-cache
      run: |
        echo "::set-output name=dir::$(pip cache dir)"
    - name: Cache PyPI
      uses: actions/cache@v2
      with:
        key: ${{ inputs.pip-cache-key }}
        path: ${{ steps.pip-cache.outputs.dir }}
    - name: Get Poetry
      run: |
        pip install -r ci/poetry-requirements.txt
    - name: Get poetry cache dir
      id: poetry-cache
      run: |
        echo "::set-output name=dir::$(poetry config cache-dir)"
    - name: Cache Poetry
      uses: actions/cache@v2
      with:
        key: ${{ inputs.poetry-cache-key }}
        path: ${{ steps.poetry-cache.outputs.dir }}
    - name: Install dependencies
      run: |
        poetry install